version: "3.8"

name: gRPC-Task
services:
  postgres:
    image: postgres
    container_name: grpc-task_database_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: grpc-task
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
